name: LivesPlugin
version: ${project.version}
main: org.novagladecode.livesplugin.LivePlugin
api-version: 1.21
author: YourName
description: A lives system with levels and effects

commands:
  invis:
    description: Toggle invisibility (requires level 9+)
    usage: /invis
  life:
    description: Manage your levels and lives
    usage: /life <level|withdraw|set|reset|help>
  airboost:
    description: Boost yourself into the air (requires level 15+)
    usage: /airboost
  dragonbreath:
    description: Spawn dragon breath (requires Dragon Egg)
    usage: /dragonbreath
  weapon:
    description: Give custom weapons (OP only)
    usage: /weapon give <warden|nether|end|chickenbow>
    permission: livesplugin.op
  nethermace:
    description: Use Nether Mace abilities
    usage: /nethermace <1|2>
  wardenmace:
    description: Use Warden Mace abilities
    usage: /wardenmace <1|2>
  endmace:
    description: Use End Mace abilities
    usage: /endmace <1|2>
  trust:
    description: Trust a player to be immune to abilities
    usage: /trust <player>
  untrust:
    description: Untrust a player
    usage: /untrust <player>