name: MaceAndMight
version: ${project.version}
main: org.novagladecode.livesplugin.LivePlugin
api-version: 1.21
author: YourName
description: Mace & Might SMP Plugin

commands:
  might:
    description: Main plugin command (Mace Controls)
    usage: /might <subcommand>
    aliases: [mace]
  wardenmace:
    description: Warden Mace abilities
    usage: /wardenmace <1/2>
  nethermace:
    description: Nether Mace abilities
    usage: /nethermace <1/2>
  endmace:
    description: End Mace abilities
    usage: /endmace <1/2>
  trust:
    description: Trust a player to avoid friendly fire from maces
    usage: /trust <player>
  untrust:
    description: Untrust a player
    usage: /untrust <player>
  weapon:
    description: Get custom weapons
    usage: /weapon get <name>
permissions:
  livesplugin.admin:
    description: Admin permissions
    default: op