name: ForgeboundSMP
version: ${project.version}
main: org.novagladecode.livesplugin.LivePlugin
api-version: 1.21
author: YourName
description: Forgebound SMP Plugin

commands:
  forge:
    description: Main plugin command (Forge Controls)
    usage: /forge <subcommand>
    aliases: [mace]
  wardenmace:
    description: Warden Mace abilities
    usage: /wardenmace <1/2>
  nethermace:
    description: Nether Mace abilities
    usage: /nethermace <1/2>
  endmace:
    description: End Mace abilities
    usage: /endmace <1/2>
  ghostblade:
    description: Ghostblade abilities
    usage: /ghostblade <1/2>
  dragonblade:
    description: Dragonblade abilities
    usage: /dragonblade <1/2>
  mistblade:
    description: Mistblade abilities
    usage: /mistblade <1/2>
  soulblade:
    description: Soulblade abilities
    usage: /soulblade <1/2>
  trust:
    description: Trust a player to avoid friendly fire from maces
    usage: /trust <player>
  untrust:
    description: Untrust a player
    usage: /untrust <player>
  weapon:
    description: Get custom weapons
    usage: /weapon get <name>
permissions:
  livesplugin.admin:
    description: Admin permissions
    default: op